version: '3.1'

services:
  app:
    image: "rest:latest"
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'config_system'